// 매뉴얼용 화면 캡처. 빈 DB 로 띄운 서버(8094)에 예시 데이터를 넣고 키오스크(태블릿)·스태프(폰) 화면을 순서대로 찍는다.
// 사용: node e2e/_capture.mjs <출력폴더>   (서버는 미리 8094 에 KIOSK_STAFF_PIN=1234 로)
import { chromium } from '@playwright/test'
import fs from 'node:fs'

const OUT = process.argv[2]
const BASE = 'http://localhost:8094'
fs.mkdirSync(OUT, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome' })

// ── 예시 데이터 ──
const ctx = await browser.newContext({ baseURL: BASE })
const req = ctx.request
const login = await (await req.post('/api/staff-auth/login', { data: { pin: '1234' } })).json()
const H = { 'X-Staff-Token': login.token }
const post = (p, data) => req.post(p, { headers: H, data })
const c1 = await (await post('/api/staff/coupons', { name: '김영희', phone: '010-1234-5678', amount: 20000 })).json()
await post('/api/staff/coupons', { name: '박철수', phone: '010-2222-3333', amount: 30000 })
await post('/api/staff/coupons', { name: '김영희', phone: '010-9999-0001', amount: 20000 })
const order = (data) => req.post('/api/orders', { data: { receiveType: 'STORE', payMethod: 'CASH', ...data } })
await order({ customerName: '이수진', lines: [{ variantId: 1001, quantity: 2, optionIds: [1] }, { variantId: 3002, quantity: 1 }], cashGiven: 10000 })
await order({ customerName: '최민호', receiveType: 'DELIVERY', placeId: 101, payMethod: 'TRANSFER', lines: [{ variantId: 1201, quantity: 1 }] })
await order({ customerName: '김영희', payMethod: 'COUPON', couponId: c1.id, useFreeDrink: true, lines: [{ variantId: 3101, quantity: 1 }, { variantId: 1101, quantity: 1 }] })
await order({ customerName: '전도사님', payMethod: 'NONE', lines: [{ variantId: 1002, quantity: 1, staffFreeQty: 1 }] })
const edited = await (await order({ customerName: '정하나', lines: [{ variantId: 3101, quantity: 1 }], cashGiven: 5000 })).json()
await req.put(`/api/staff/orders/${edited.id}`, { headers: H, data: { customerName: '정하나', receiveType: 'STORE', lines: [{ variantId: 3101, quantity: 2 }], memo: '얼음 적게' } })

const shot = async (page, name) => { await page.waitForTimeout(350); await page.screenshot({ path: `${OUT}/${name}.png` }) }

// ── 키오스크 (갤럭시탭 S6 Lite 세로 800×1333) ──
const k = await browser.newPage({ viewport: { width: 800, height: 1333 }, deviceScaleFactor: 1 })
await k.goto(BASE + '/kiosk')
await shot(k, 'k01-menu')
const add = async (menu, label) => {
  const card = k.locator('.menu-card').filter({ has: k.locator('.name').getByText(menu, { exact: true }) })
  await card.getByRole('button', { name: label ? new RegExp('^' + label) : '담기' }).click()
}
await add('아메리카노', 'ICE'); await add('아메리카노', 'ICE'); await add('라떼', 'HOT')
await shot(k, 'k02-menu-added')
await k.getByRole('button', { name: /주문 확인/ }).click()
await k.locator('.cart-line-wrap').filter({ hasText: '아메리카노' }).getByRole('button', { name: '샷 추가' }).click()
await shot(k, 'k03-cart')
await k.getByRole('button', { name: /주문하기/ }).click()
await shot(k, 'k04-receive')
await k.getByRole('button', { name: /배달/ }).click()
await shot(k, 'k05-place')
await k.getByRole('button', { name: '식당' }).click()
await shot(k, 'k06-payment')
await k.getByRole('button', { name: /계좌이체/ }).click()
await shot(k, 'k07-transfer')
await k.getByRole('button', { name: '‹ 이전' }).click()
await k.getByRole('button', { name: /현금/ }).click()
await k.getByRole('button', { name: '10,000원' }).click()
await shot(k, 'k08-cash')
await k.getByRole('button', { name: /다음/ }).click()
await shot(k, 'k09-name')
await k.getByRole('button', { name: /직접 입력/ }).click()
await k.getByPlaceholder('이름').fill('홍길동')
await shot(k, 'k10-name-typing')
await k.getByRole('button', { name: '주문 완료' }).click()
await shot(k, 'k11-done')
// 쿠폰 흐름
await k.getByRole('button', { name: /처음으로/ }).click()
await add('아포카토'); await add('아메리카노', 'ICE')
await k.getByRole('button', { name: /주문 확인/ }).click()
await k.getByRole('button', { name: /주문하기/ }).click()
await k.getByRole('button', { name: /카페에서 받기/ }).click()
await k.getByRole('button', { name: /쿠폰/ }).click()
await shot(k, 'k12-coupon-name')
await k.getByRole('button', { name: /직접 입력/ }).click()
await k.getByPlaceholder('이름').fill('김영희')
await k.getByRole('button', { name: '쿠폰 조회' }).click()
await shot(k, 'k13-coupon-pick')
await k.getByRole('button', { name: '‹ 다른 이름' }).click()
if (await k.getByRole('button', { name: /직접 입력/ }).count()) await k.getByRole('button', { name: /직접 입력/ }).click()
await k.getByPlaceholder('이름').fill('박철수')
await k.getByRole('button', { name: '쿠폰 조회' }).click()
await shot(k, 'k14-coupon-found')
await k.getByRole('button', { name: /무료 1잔 쓰기/ }).click()
await shot(k, 'k15-coupon-free')
// 사역자 칩
await k.getByRole('button', { name: /처음으로/ }).click()
await add('바닐라라떼', 'ICE'); await add('바닐라라떼', 'ICE'); await add('바닐라라떼', 'ICE')
await k.getByRole('button', { name: /주문 확인/ }).click()
await k.locator('.cart-line-wrap').first().getByRole('button', { name: '사역자' }).click()
await k.locator('.cart-line-wrap').first().getByRole('button', { name: '사역자' }).click()
await shot(k, 'k16-cart-staff')
await k.close()

// ── 스태프 (폰 412×915) ──
const s = await browser.newPage({ viewport: { width: 412, height: 915 }, deviceScaleFactor: 2 })
await s.goto(BASE + '/staff')
await shot(s, 's01-login')
for (const d of '1234') await s.getByRole('button', { name: d, exact: true }).click()
await s.waitForSelector('.order-card')
await shot(s, 's02-orders')
const card = s.locator('.order-card').filter({ hasText: '정하나' })
await card.scrollIntoViewIfNeeded()
await shot(s, 's03-order-settle')
await card.getByRole('button', { name: '수정' }).click()
await shot(s, 's04-edit')
await s.getByRole('button', { name: '닫기' }).click()
await card.getByRole('button', { name: '취소', exact: true }).click()
await shot(s, 's05-cancel')
await card.getByRole('button', { name: '취소 안 함' }).click()
await s.locator('.order-card').filter({ hasText: '이수진' }).getByRole('button', { name: /완료/ }).click()
await s.getByRole('button', { name: '완료', exact: true }).click()
await shot(s, 's06-done')
await s.getByRole('button', { name: '쿠폰' }).click()
await shot(s, 's07-coupon')
await s.getByPlaceholder('쿠폰 주인 이름').fill('박철수')
await s.getByRole('button', { name: '조회' }).click()
await s.waitForSelector('.history-row')
await shot(s, 's08-coupon-card')
await s.getByPlaceholder('쿠폰 주인 이름').fill('신규손님')
await s.getByRole('button', { name: '조회' }).click()
await s.getByPlaceholder('010-0000-0000').fill('01055556666')
await shot(s, 's09-coupon-register')
await s.getByRole('button', { name: '매출' }).click()
await s.waitForSelector('.day-card')
await s.locator('.day-head').first().click()
await shot(s, 's10-report')
await s.getByRole('button', { name: '설정' }).click()
await shot(s, 's11-settings')
await s.getByRole('button', { name: '메뉴', exact: true }).click()
await s.locator('.cat-head').first().click()
await shot(s, 's12-settings-menu')
await s.getByRole('button', { name: '＋ 새 메뉴' }).click()
await shot(s, 's13-menu-modal')
await s.getByRole('button', { name: '닫기' }).click()
await s.getByRole('button', { name: '설정으로' }).click()
await s.getByRole('button', { name: '옵션', exact: true }).click()
await shot(s, 's14-settings-options')
await s.getByRole('button', { name: '설정으로' }).click()
await s.getByRole('button', { name: '카테고리' }).click()
await shot(s, 's15-settings-categories')
await s.getByRole('button', { name: '설정으로' }).click()
await s.getByRole('button', { name: '배달 장소' }).click()
await shot(s, 's16-settings-places')
await s.close()
await browser.close()
console.log('captured', fs.readdirSync(OUT).length)
